name: CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Test Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run lint
          npm test

  backend:
    name: Backend Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports: ['5432:5432']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install & Test Backend
        working-directory: backend
        run: |
          pip install -r requirements.txt
          pytest

  e2e:
    name: Cypress End-to-End
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --workspace=frontend

      - name: Start app
        run: npm start --workspace=frontend &
      
      - name: Wait for app
        uses: jakejarvis/wait-action@v0.1.3
        with:
          timeout: '60s'
          url: 'http://localhost:3000'

      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          browser: chrome
